
import java.awt.Graphics2D;
import java.awt.Label;
import java.awt.event.ActionListener;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gui.java
 *
 * Created on Jan 31, 2011, 7:08:33 PM
 */

/**
 *
 * @author nitin
 */
public class gui extends javax.swing.JFrame {
    public int y[]=new int[1024];
    /** Creates new form gui */
    public gui() {
        initComponents();
        jCheckBox1.setVisible(false);
        jCheckBox10.setVisible(false);
        jCheckBox2.setVisible(false);
        jCheckBox3.setVisible(false);
        jCheckBox4.setVisible(false);
        jCheckBox5.setVisible(false);
        jCheckBox6.setVisible(false);
        jCheckBox7.setVisible(false);
        jCheckBox8.setVisible(false);
        jCheckBox9.setVisible(false);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picLabel = new javax.swing.JLabel();
        sourceButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        refineButton = new javax.swing.JButton();
        imgLabel1 = new javax.swing.JLabel();
        imgLabel2 = new javax.swing.JLabel();
        imgLabel3 = new javax.swing.JLabel();
        imgLabel6 = new javax.swing.JLabel();
        imgLabel5 = new javax.swing.JLabel();
        imgLabel4 = new javax.swing.JLabel();
        imgLabel7 = new javax.swing.JLabel();
        imgLabel8 = new javax.swing.JLabel();
        imgLabel9 = new javax.swing.JLabel();
        imgLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HYBRID CBIR INTERFACE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(picLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 11, 128, 128));

        sourceButton.setText("Select Source");
        sourceButton.setToolTipText("Select source image");
        sourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sourceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 145, -1, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 310, 97, -1));
        searchButton.getAccessibleContext().setAccessibleDescription("Search image database");

        refineButton.setText("Refine");
        refineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refineButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 393, 97, -1));
        refineButton.getAccessibleContext().setAccessibleDescription("Refine selected images");

        getContentPane().add(imgLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 128, 128));
        getContentPane().add(imgLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 254, 128, 128));
        getContentPane().add(imgLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 254, 128, 128));
        getContentPane().add(imgLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 395, 128, 128));
        getContentPane().add(imgLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 395, 128, 128));
        getContentPane().add(imgLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 395, 128, 128));
        getContentPane().add(imgLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 535, 128, 128));
        getContentPane().add(imgLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 535, 128, 128));
        getContentPane().add(imgLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 535, 128, 128));
        getContentPane().add(imgLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 535, 128, 128));
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 360, -1, -1));
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 360, -1, -1));
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 500, -1, -1));
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 500, -1, -1));
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 640, -1, -1));
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 640, -1, -1));
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("."));
        int retVal = fc.showOpenDialog(this);
        if( retVal == fc.APPROVE_OPTION){
            fileName = fc.getSelectedFile().getAbsolutePath();
            picLabel.setIcon(new ImageIcon(fileName));
        }
    }//GEN-LAST:event_sourceButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (fileName.equals("/0"))
            JOptionPane.showMessageDialog(null, "Select Source Image!", "Alert", JOptionPane.ERROR_MESSAGE);
        else{
        
         BufferedImage bsrc = null;
            try {
                bsrc = ImageIO.read(new File(fileName));
              int width=128,height=128;
  		BufferedImage bdest =
      new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
   Graphics2D g = bdest.createGraphics();
   AffineTransform at =
      AffineTransform.getScaleInstance((double)width/bsrc.getWidth(),
          (double)height/bsrc.getHeight());
   g.drawRenderedImage(bsrc,at);
   ImageIO.write(bdest,"JPG",new File(fileName));
    } catch (IOException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        m = new master();
        m.initial();

        m.masfun(fileName);
        imgLabel1.setIcon(new ImageIcon(m.filename[m.obj[0].num-1]));
        imgLabel2.setIcon(new ImageIcon(m.filename[m.obj[1].num-1]));
        imgLabel3.setIcon(new ImageIcon(m.filename[m.obj[2].num-1]));
        imgLabel4.setIcon(new ImageIcon(m.filename[m.obj[3].num-1]));
        imgLabel5.setIcon(new ImageIcon(m.filename[m.obj[4].num-1]));
        imgLabel6.setIcon(new ImageIcon(m.filename[m.obj[5].num-1]));
        imgLabel7.setIcon(new ImageIcon(m.filename[m.obj[6].num-1]));
        imgLabel8.setIcon(new ImageIcon(m.filename[m.obj[7].num-1]));
        imgLabel9.setIcon(new ImageIcon(m.filename[m.obj[8].num-1]));
        imgLabel10.setIcon(new ImageIcon(m.filename[m.obj[9].num-1]));
        jCheckBox1.setVisible(true);
        jCheckBox2.setVisible(true);
        jCheckBox3.setVisible(true);
        jCheckBox4.setVisible(true);
        jCheckBox5.setVisible(true);
        jCheckBox6.setVisible(true);
        jCheckBox7.setVisible(true);
        jCheckBox8.setVisible(true);
        jCheckBox9.setVisible(true);
        jCheckBox10.setVisible(true);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void refineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refineButtonActionPerformed

        checked[0]=jCheckBox1.isSelected()? 1:0;
        checked[1]=jCheckBox2.isSelected()? 1:0;
        checked[2]=jCheckBox3.isSelected()? 1:0;
        checked[3]=jCheckBox4.isSelected()? 1:0;
        checked[4]=jCheckBox5.isSelected()? 1:0;
        checked[5]=jCheckBox6.isSelected()? 1:0;
        checked[6]=jCheckBox7.isSelected()? 1:0;
        checked[7]=jCheckBox8.isSelected()? 1:0;
        checked[8]=jCheckBox9.isSelected()? 1:0;
        checked[9]=jCheckBox10.isSelected()? 1:0;
      //  System.out.print(m.filename[m.obj[0].num-1]);
  /*      imgLabel1= new JLabel();
        imgLabel2= new JLabel();
        imgLabel3= new JLabel();
        imgLabel4= new JLabel();
        imgLabel5= new JLabel();
        imgLabel6= new JLabel();
        imgLabel7= new JLabel();
        imgLabel8= new JLabel();
        imgLabel9= new JLabel();
        imgLabel10= new JLabel();
         imgLabel1.setVisible(true);
        imgLabel2.setVisible(true);
        imgLabel3.setVisible(true);
        imgLabel4.setVisible(true);
        imgLabel5.setVisible(true);
        imgLabel6.setVisible(true);
        imgLabel7.setVisible(true);
        imgLabel8.setVisible(true);
        imgLabel9.setVisible(true);
        imgLabel10.setVisible(true);
   */
     //  m = new master(fileName);
          int c=0;
        int rel[] =new int[9];
        for(int i=0;i<10;i++)
         {
             if(checked[i]==1){
                 rel[c]=m.obj[i].num-1;
                 System.out.println(rel[c++]);
                   }
         }
         refine ob=new refine();
        m.flag1++;
        m.mas[m.fname.length]=ob.func(rel,c,m.mas,m.fname.length);
        System.out.println();
        System.out.println("flag="+m.flag1);
        m.masfun(fileName);

//        if(checked[0]==1){
            imgLabel1.setIcon(new ImageIcon(m.filename[m.obj[0].num-1]));
  //      }
    //    if(checked[1]==1)
            imgLabel2.setIcon(new ImageIcon(m.filename[m.obj[1].num-1]));
      //  if(checked[2]==1)
            imgLabel3.setIcon(new ImageIcon(m.filename[m.obj[2].num-1]));
        //if(checked[3]==1)
            imgLabel4.setIcon(new ImageIcon(m.filename[m.obj[3].num-1]));
        //if(checked[4]==1)
            imgLabel5.setIcon(new ImageIcon(m.filename[m.obj[4].num-1]));
        //if(checked[5]==1)
            imgLabel6.setIcon(new ImageIcon(m.filename[m.obj[5].num-1]));
        //if(checked[6]==1)
            imgLabel7.setIcon(new ImageIcon(m.filename[m.obj[6].num-1]));
        //if(checked[7]==1)
            imgLabel8.setIcon(new ImageIcon(m.filename[m.obj[7].num-1]));
        //if(checked[8]==1)
            imgLabel9.setIcon(new ImageIcon(m.filename[m.obj[8].num-1]));
        //if(checked[9]==1)
            imgLabel10.setIcon(new ImageIcon(m.filename[m.obj[9].num-1]));

      
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);


        getContentPane().add(imgLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 128, 128));
        getContentPane().add(imgLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 254, 128, 128));
        getContentPane().add(imgLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 254, 128, 128));
        getContentPane().add(imgLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 395, 128, 128));
        getContentPane().add(imgLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 395, 128, 128));
        getContentPane().add(imgLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 395, 128, 128));
        getContentPane().add(imgLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 535, 128, 128));
        getContentPane().add(imgLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 535, 128, 128));
        getContentPane().add(imgLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 535, 128, 128));
        getContentPane().add(imgLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 535, 128, 128));
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 360, -1, -1));
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 360, -1, -1));
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 500, -1, -1));
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 500, -1, -1));
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 640, -1, -1));
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 640, -1, -1));
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, -1, -1));
        pack();
    }//GEN-LAST:event_refineButtonActionPerformed
   public int[] refunc()
    {
       return y;
      }
   /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    //    java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run() {
                new gui().setVisible(true);
    //        }
    //    });
    }
    public master m;
    public String fileName="/0";
    public int checked[]=new int[10];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLabel1;
    private javax.swing.JLabel imgLabel10;
    private javax.swing.JLabel imgLabel2;
    private javax.swing.JLabel imgLabel3;
    private javax.swing.JLabel imgLabel4;
    private javax.swing.JLabel imgLabel5;
    private javax.swing.JLabel imgLabel6;
    private javax.swing.JLabel imgLabel7;
    private javax.swing.JLabel imgLabel8;
    private javax.swing.JLabel imgLabel9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel picLabel;
    private javax.swing.JButton refineButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton sourceButton;
    // End of variables declaration//GEN-END:variables

}
